version: "3"
services:
  azure-vote-back:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: azure-vote-back1
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6380:6379"

  azure-vote-front:
    build: ./azure-vote
    image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
    container_name: azure-vote-front1
    environment:
      REDIS: azure-vote-back
    ports:
      - "8083:80"
